### ISSUE TITLE
i18n error in nextjs

### ISSUE THREAD

**Issue by markolofsen** [i18next/i18next#1101]
## Example name
i18n error

## Describe the bug
Repo example: https://github.com/markolofsen/nextjs

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. yarn dev --> http://localhost:3000/about
2. See error: Internal Server Error

## Expected behavior
My variable {t('pureComponent')} in /pages/about.js doesn't work

## System information
 - OS: MacOS
 - Version of Next.js: canary (latest)

## Additional context
```
TypeError: Cannot set property 'toJSON' of undefined
    at I18n.module.exports../i18n.js.i18n.getInitialProps (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/about.js:143:19)
    at Function._callee$ (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/about.js:327:91)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/about.js:284:103)
    at _next (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/about.js:286:194)
    at <anonymous>
TypeError: Cannot read property 'sheetsRegistry' of undefined
    at Function.module.exports../pages/_document.js.MyDocument.getInitialProps (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/_document.js:384:29)
    at _callee$ (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/lib/utils.js:135:30)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at /Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/Users/mark/Documents/htdocs/nextjs/node_modules/core-js/library/modules/_export.js:36:28)
    at /Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:23:12
    at loadGetInitialProps (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/lib/utils.js:98:31)
    at _callee3$ (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/server/render.js:339:51)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
TypeError: Cannot read property 'sheetsRegistry' of undefined
    at Function.module.exports../pages/_document.js.MyDocument.getInitialProps (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/_document.js:384:29)
    at _callee$ (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/lib/utils.js:135:30)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at /Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/Users/mark/Documents/htdocs/nextjs/node_modules/core-js/library/modules/_export.js:36:28)
    at /Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:23:12
    at loadGetInitialProps (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/lib/utils.js:98:31)
    at _callee3$ (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/server/render.js:339:51)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
> Disposing inactive page(s): /about

```

**Comment by jamuhl** [comment]
looks like caused by: https://github.com/markolofsen/nextjs/blob/master/i18n.js#L42 -> try adding a check there if req.i18n is set at all before adding toJSON function on it

**Comment by markolofsen** [comment]
@jamuhl I think problem in express server.
Path not found http://localhost:3000/locales/en/common.json
But... thats config from nextjs example

**Comment by markolofsen** [comment]
@jamuhl I'm updated a repo.
https://github.com/markolofsen/nextjs/blob/d11ddcdccb3980e1fb650045ccea2e1028de8c2e/server.js#L60

**Comment by jamuhl** [comment]
?

**Comment by markolofsen** [comment]
I'm shocked too... That's basis express configuration from https://github.com/zeit/next.js/blob/canary/examples/with-react-i18next/server.js

**Comment by jamuhl** [comment]
and? that sample works...or does it not?

**Comment by jamuhl** [comment]
at least did for me

**Comment by markolofsen** [comment]
Oups, sorry. Forgot update my repo. Check again please.
Check this path http://localhost:3000/locales/en/common.json

**Comment by jamuhl** [comment]
https://github.com/zeit/next.js/blob/canary/examples/with-react-i18next/package.json#L7

that is the difference

**Comment by markolofsen** [comment]
@jamuhl Thank's really)

**Comment by chayakornwc** [comment]
i have same this problem, too many lost of sheetsRegistry.

**Comment by jamuhl** [comment]
@chayakornwc sorry don't understand your issue

**Comment by Manubi** [comment]
I am having the same error:
TypeError: Cannot read property 'sheetsRegistry' of undefined
when using Next.js with i18n. 
Unfortunately your pictures are not online anymore... still any suggestions? :)

**Comment by jamuhl** [comment]
@Manubi are you using https://github.com/isaachinman/next-i18next ?!?

anyway next.js related issues are better asked there...as the issue has todo with next.js and your setup...not with i18next in particular...

did you set i18n.toJSON = () => () ---> not serializing the world for initialProps...
