### ISSUE TITLE
Issue with node.js after updating to v17.0.0

### ISSUE THREAD

**Issue by Poyoman39** [i18next/i18next#1258]
Hi,
I just updated i18next to the last version (17.0.0), which leads to a bug when run on node.js

Here is the bug : 

```
/home/johan/code/swishlive/server/node_modules/i18next/index.js:5
module.exports.default = main;
                       ^

TypeError: Cannot set property 'default' of undefined
    at Object.<anonymous> (/home/.../server/node_modules/i18next/index.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/.../server/dependancies/i18n/index.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

```

It looks like the recent update broke the compatibility with "require" way of import.

My import looks like so : 
```
const i18next = require('i18next');
```

Note: Issue does not happen using v16.0.0

**Comment by jamuhl** [comment]
can you try i18next@17.0.1

**Comment by shian15810** [comment]
@jamuhl I've tried it, issue resolved.

**Comment by Poyoman39** [comment]
Solved for me too ! ;) Thank you for the fix !
