### ISSUE TITLE
Not honouring hyphenated names when loading languages

### ISSUE THREAD

**Issue by Nytelife26** [i18next/i18next#1521]
## 🐛 Bug Report
i18next does not seem to honour hyphenated directory names on my system when loading namespaces.  
My project works on Windows and MacOS, but does not seem to on my Arch Linux laptop.  

I have a language folder, located at `languages/en-us`. None of the keys are loading or resolving properly.  
In order to diagnose the issue I enabled debug in the i18n settings.

```js
i18next: initialized {
  debug: true,
  initImmediate: false,
  ns: [ 'core', 'fun', 'global', 'moderation', 'utilities' ],
  defaultNS: 'global',
  fallbackLng: [ 'en-us' ],
  fallbackNS: false,
  whitelist: false,
  nonExplicitWhitelist: false,
  supportedLngs: false,
  nonExplicitSupportedLngs: false,
  load: 'all',
  preload: [ 'en-us' ],
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
```
As you can see, it detects the namespaces and the language just fine in the initialization.  
However, when loading the language,

```js
i18next::backendConnector: loading namespace utilities for language en failed Error: ENOENT: no such file or directory, open '/home/nytelife26/projects/syrus-bot/src/languages/en/utilities.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at readFileInNodeSync (/home/nytelife26/projects/syrus-bot/node_modules/i18next-fs-backend/cjs/readFile.js:30:13)
    at readFileSync (/home/nytelife26/projects/syrus-bot/node_modules/i18next-fs-backend/cjs/readFile.js:102:12)
    at Backend.read (/home/nytelife26/projects/syrus-bot/node_modules/i18next-fs-backend/cjs/index.js:71:54)
    at Connector.read (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1583:34)
    at Connector.loadOne (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1641:12)
    at /home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1617:16
    at Array.forEach (<anonymous>)
    at Connector.prepareLoading (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1616:21)
    at Connector.load (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1623:12)
    at I18n.loadResources (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1975:40)
    at setLng (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:2071:16)
    at I18n.changeLanguage (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:2081:9)
    at load (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1917:16)
    at I18n.init (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1929:9) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/nytelife26/projects/syrus-bot/src/languages/en/utilities.json'
}
```
It removes the hyphenated section of the name. This is unexpected behaviour.

## To Reproduce

1. Use i18n on a UNIX system similar to mine
2. Create a language directory with a hyphenated name
3. Get i18n to attempt to load the namespaces

```js
i18n: {
	defaultMissingKey: "missing",
	defaultNS: "global",
	i18next: {
		preload: ["en-us"],
		load: "all",
		fallbackLng: "en-us",
		initImmediate: false,
		interpolation: {
			escapeValue: false
		}
	}
}
```

## Expected behavior

I expected i18n to load the language with the full name, honouring the hyphen.

## Your Environment

- *runtime version*: node v14.x
- *i18next version*: 19.8.3
- *os*: Arch Linux

**Comment by jamuhl** [comment]
Could you please share more details about what backend was used ... or even better open an issue in the backend repository...as i18next itself does not load anything without a backend.

**Comment by Nytelife26** [comment]
Apologies, @jamuhl. In that case, it may be wise to transfer this issue to [i18next-fs-backend](https://github.com/i18next/i18next-fs-backend) if possible.
