### ISSUE TITLE
how to load  i18next in webworker? 

### ISSUE THREAD

**Issue by mredodos** [i18next/i18next#1736]
hi, i use the library for react i have some string with date message in webworker.  if i try to import i18next from "../i18n" in the webworker when build my app return error because try to load window and in the webworker window is not defined 

`external window "React":1 Uncaught (in promise) ReferenceError: window is not defined
    at Object.react (external window "React":1:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module../node_modules/react-i18next/dist/es/context.js (utils.js:252:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module../src/i18n.js (db.js:12:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module../src/worker/updateDB.worker.js (i18n.js:28:3)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:32:180
    at Function.__webpack_require__.O (chunk loaded:25:1)`

how can i use i18next in webworker?

**Comment by jamuhl** [comment]
Webworker runs in isolation. You will need a own instance there loading all translations. 

so short answer is - don‘t do it in the worker.

**Comment by mredodos** [comment]
I basically send a string from the webworker to a function in a component and then that component processes the message to be displayed on the screen.
I could instead of sending the string from the webworker, send only the date variables and such and then send the translated string directly.

BUT when i try to import useTranslate react return that 

`Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.T (react-dom.min.js?ver=17.0.1:99:241)
    at c.useContext (react.min.js?ver=17.0.1:29:462)
    at useTranslation (useTranslation.js:15:24)
    at updateDb.js:13:33
    at Tj (react-dom.min.js?ver=17.0.1:179:399)
    at unstable_runWithPriority (react.min.js?ver=17.0.1:24:26)
    at Za (react-dom.min.js?ver=17.0.1:73:8)
    at Ra (react-dom.min.js?ver=17.0.1:178:368)
    at react-dom.min.js?ver=17.0.1:178:275
    at R (react.min.js?ver=17.0.1:16:298)
    at MessagePort.ua.port1.onmessage (react.min.js?ver=17.0.1:22:360)`

**Comment by jamuhl** [comment]
idk. a codesandbox would be nice to follow what you try todo. but to say. we use webworkers and react-i18next without issues. just letting the ui handle the translating step

**Comment by mredodos** [comment]
I have a component called flashmessage, which is responsible for displaying a message on the screen to notify the user if the operation was successful or if there is some error. 

the webworker in this moment sends the text message with some dates(i warn the user that the update will be done in an hour) to a component that check if the local database is updated and this component sends then the text to the flashmessage component.

if i understand well what you suggest, i don't have to send the text message anymore, i simply send the dates to the string with the t() function, correct?

**Comment by mredodos** [comment]
ok thx i have solved all the problem!
