### ISSUE TITLE
RangeError: Map maximum size exceeded

### ISSUE THREAD

**Issue by koji--** [i18next/i18next#2001]
## 💥 Regression Report

When I upgraded from v22.5.1 to v23.2.11, the following error occurred when compiling tsc.

```
$ yarn tsc
yarn run v1.22.19
$ npx tsc --noemit
/path/to/node_modules/typescript/lib/tsc.js:114743
      throw e;
      ^

RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at recursiveTypeRelatedTo (/path/to/node_modules/typescript/lib/tsc.js:60316:18)
    at isRelatedTo (/path/to/node_modules/typescript/lib/tsc.js:59741:122)
    at typeRelatedToSomeType (/path/to/node_modules/typescript/lib/tsc.js:60002:25)
    at unionOrIntersectionRelatedTo (/path/to/node_modules/typescript/lib/tsc.js:59922:16)
    at structuredTypeRelatedToWorker (/path/to/node_modules/typescript/lib/tsc.js:60481:23)
    at structuredTypeRelatedTo (/path/to/node_modules/typescript/lib/tsc.js:60323:21)
    at recursiveTypeRelatedTo (/path/to/node_modules/typescript/lib/tsc.js:60293:19)
    at isRelatedTo (/path/to/node_modules/typescript/lib/tsc.js:59741:122)
    at structuredTypeRelatedToWorker (/path/to/node_modules/typescript/lib/tsc.js:60553:17)

Node.js v20.3.1
error Command failed with exit code 1.
```

So, I added the following console.log to the line where the error occurred(`/path/to/node_modules/typescript/lib/tsc.js`) and confirmed.

```
60316         console.log("id: ", id);                                                                                        
60317         console.log("relation: ", relation);                                                                            
60318         relation.set(id, (reportErrors2 ? 4 /* Reported */ : 0) | 2 /* Failed */ | propagatingVarianceFlags); 
```

When I looked at the log, it seemed that the number of records in Map was significantly different.

```
$ tail -n 200 23-2-11-tscbuild.log | grep Map
relation:  Map(16777216) {
$ tail -n 200 22-5-1-tscbuild.log | grep Map
relation:  Map(84358) {
```

The above is a business environment, so when I created a separate environment and tried it, the Range Error did not occur, but the following differences were observed in the number of records in the Map.

https://github.com/koji--/i18n-test
```
$ tail -n 200 23-2-11-tscbuild.log | grep Map
relation:  Map(14624) {
$ tail -n 200 22-5-1-tscbuild.log | grep Map
relation:  Map(4761) {
```

Since the error occurrence is different, I made another issue, but it may be a similar problem to #1991.

The error itself has not been reproduced, but I will report it as an issue.

## Last working version

Worked up to version: v22.5.1

Stopped working in version: v23.2.11

## Expected behavior

No errors when compiling tsc.

## Your Environment

- *runtime version*: node v20.3.1
- *i18next version*: 23.2.11
- *os*: Mac, Linux(ubuntu latest on github actions)

**Comment by adrai** [comment]
Can you try if it's better with v23.3.0?

**Comment by ruudandriessen** [comment]
I can't speak for the author - but we had the same issue on our side. For us it's resolved on 23.3 😄

**Comment by koji--** [comment]
@adrai thank you. I checked again in the environment for business and the environment created for experiment.

business and the environment:
```
$ tail -n 200 23-3-0-tscbuild.log | grep Map
relation:  Map(97638) {
```

https://github.com/koji--/i18n-test
```
tail -n 200 23-3-0-tscbuild.log | grep Map
relation:  Map(14624) {
```

Range Error no longer occurs in the v23.3.0 business environment, so I think this issue has been resolved.
