### ISSUE TITLE
RangeError: Map maximum size exceeded

### ISSUE THREAD

**Issue by AndreyTheWeb** [i18next/i18next#2204]
## 💥 Regression Report

When I upgraded from v22.4.9 to v"23.11.5, the following error occurred when compiling tsc.

`> tsc -p tsconfig.base.json --noEmit --pretty --incremental true --tsBuildInfoFile .cache/ts_lint
/builds/my-path/node_modules/typescript/lib/tsc.js:118651
      throw e;
      ^
RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at checkTypeRelatedTo (/builds/my-path/node_modules/typescript/lib/tsc.js:610[46](https://ci.unitedline.net/my-path/-/jobs/3004328#L46):16)
    at isTypeRelatedTo (/builds/my-path/node_modules/typescript/lib/tsc.js:60967:14)
    at isTypeSubtypeOf (/builds/my-path/node_modules/typescript/lib/tsc.js:600[48](https://ci.unitedline.net/my-path/-/jobs/3004328#L48):12)
    at extractRedundantTemplateLiterals (/builds/my-path/node_modules/typescript/lib/tsc.js:57899:13)
    at getIntersectionType (/builds/my-path/node_modules/typescript/lib/tsc.js:57970:127)
    at getCrossProductIntersections (/builds/my-path/node_modules/typescript/lib/tsc.js:58069:17)
    at getIntersectionType (/builds/my-path/node_modules/typescript/lib/tsc.js:58031:32)
    at instantiateTypeWorker (/builds/my-path/node_modules/typescript/lib/tsc.js:59884:106)
    at instantiateTypeWithAlias (/builds/my-path/node_modules/typescript/lib/tsc.js:598[51](https://ci.unitedline.net/my-path/-/jobs/3004328#L51):20)
Node.js v20.11.0`

## Last working version

Worked up to version: X.X.X

Stopped working in version: Y.Y.Y

## To Reproduce

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the results here
```

## Your Environment

- runtime version: node v20.11.0
- i18next version: 23.11.5
- os: Mac, Linux(ubuntu latest on gitlab pipelined)

**Comment by adrai** [comment]
please provide a minimal reproducible example project

**Comment by AndreyTheWeb** [comment]
@adrai I have two projects, the code of which I cannot show you because of the NDA, and I also cannot reproduce it in sandbox. In one project where there are few labels everything works well, but in another project where the number of labels is >1000 this error occurs

**Comment by adrai** [comment]
@AndreyTheWeb please try to create a minimal reproducible example and create a new issue... @marcalexiei will for sure have a look at it if he has all information and a bit of time...
