### ISSUE TITLE
useLocalStorage fails in Chrome with "Block third-party cookies and site data" 

### ISSUE THREAD

**Issue by julien51** [i18next/i18next#353]
In Chrome (tested in 40.0.2214.94), when `useLocalStorage` is set to true, and if the user has enabled  "Block third-party cookies and site data", then, i18next will fail:
```
 Application Cache Error event: Cache creation was blocked by the content policy
angular.js:9383 Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Error (native)
    at Object.sync._loadLocal (http://0.0.0.0:9000/bower_components/i18next/i18next.js:145:22)
    at Object.sync.load (http://0.0.0.0:9000/bower_components/i18next/i18next.js:117:22)
    at Object.init (http://0.0.0.0:9000/bower_components/i18next/i18next.js:967:19)
    at init (http://0.0.0.0:9000/bower_components/ng-i18next/dist/ng-i18next.js:35:17)
    at optionsChange (http://0.0.0.0:9000/bower_components/ng-i18next/dist/ng-i18next.js:72:4)
    at self.$get (http://0.0.0.0:9000/bower_components/ng-i18next/dist/ng-i18next.js:131:4)
    at Object.invoke (http://0.0.0.0:9000/bower_components/angular/angular.js:3697:17)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:3544:37
    at getService (http://0.0.0.0:9000/bower_components/angular/angular.js:3665:39)
```

Is there a way to fail gracefuly?

**Comment by jamuhl** [comment]
thanks for reporting...will add some try-catch block around that calls.

**Comment by jamuhl** [comment]
should be solved in next version by https://github.com/i18next/i18next/commit/08f517260ee6b1c0f2c85bde84dfc9e703cbbd93

**Comment by julien51** [comment]
Awesome, please, let me know when it goes live!



--

*Got a blog? Make following it simple: https://www.subtome.com/
<https://www.subtome.com/>*

Julien Genestoux,
http://twitter.com/julien51

+1 (415) 830 6574
+33 (0)9 70 44 76 29

**Comment by jamuhl** [comment]
new version is out.
