### ISSUE TITLE
Object #<t> has no method 'registerAppHelper'

### ISSUE THREAD

**Issue by eloyucu** [i18next/i18next#569]
I make an app on windows and all work fine... now I copy and paste to Ubuntu 14.10 (except node_modules folder, that it is created with npm install), the project isn´t working.

The error it throws is this:

```
TypeError: Object #<t> has no method 'registerAppHelper'
    at Object.<anonymous> (/home/puesto1/app/app.js:64:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

The code of the app.js is a litle big to write here, so here is the problematic block of code:

```
i18n.registerAppHelper(app)
    .serveClientScript(app)
    .serveDynamicResources(app)
    .serveMissingKeyRoute(app);
```
Here the package.json (for if there is something more that I need, or some conflicting packages):

```
{
  "name": "karting",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "express": "~4.2.0",
    "static-favicon": "~1.0.0",
    "morgan": "~1.0.0",
    "cookie-parser": "~1.0.1",
    "body-parser": "~1.0.0",
    "debug": "~0.7.4",
    "jade": "~1.3.0",
	"mongoose":"*",
	"cookie-session":"*",
	"i18next":"2.0.0",
	"extend":"*",
	"nodemailer":"*",
	"printer":"*",
	"pdfkit":"*",
	"concat-stream":"*",
	"multiparty":"*",
	"sendgrid": "^1.9.2",
	"connect-multiparty":"*"
  }
}
```

And finally the code (despite the size):
```
var express 		= require('express');
var path 			= require('path');
var favicon 		= require('static-favicon');
var logger 			= require('morgan');
var cookieParser 	= require('cookie-parser');
var bodyParser 		= require('body-parser');
var cookieSession 	= require('cookie-session');
var i18n 			= require('i18next');
var multiparty	 	= require('connect-multiparty');

var users 			= require('./routes/users');
var config 			= require('./routes/config');
var admin			= require('./routes/admin');
var karts 			= require('./routes/karts');
var residences 		= require('./routes/residences');
var employee		= require('./routes/employee');
var people_stats	= require('./routes/stats_people');
var ticket_stats	= require('./routes/stats_ticket');
var karts_stats		= require('./routes/stats_karts');
var signs			= require('./routes/signs');
var email			= require('./routes/email');
var uploader 		= require('./routes/uploader.js');

var app 			= express();


app.listen(8888);



// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

app.use(favicon());
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded());
app.use(bodyParser());
app.use(multiparty());
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
app.use(cookieSession({
    keys: ['papallama&/%><', 'magicGuru123$·"']
}));



i18n.init({
    ns: { namespaces: ['text'], defaultNs: 'text'},
    resSetPath: 'locales/__lng__/new.__ns__.json',
	preload: ['es', 'uk', 'fr', 'ge', 'ru', 'it'],
    saveMissing: true,
    debug: true,
	lng:"es",
    sendMissingTo: 'fallback',
	useCookie: false,
	detectLngFromHeaders: false,
	detectLngFromPath: false
});

i18n.registerAppHelper(app)
    .serveClientScript(app)
    .serveDynamicResources(app)
    .serveMissingKeyRoute(app);


app.use(i18n.handle);
app.use('/users', users);
app.use('/admin', admin);
app.use('/admin/configs', config);
app.use('/admin/signs', signs);
app.use('/admin/residences', residences);
app.use('/admin/karts', karts);
app.use('/admin/employee', employee);
app.use('/admin/statistics/karts',  karts_stats);
app.use('/admin/statistics/people', people_stats);
app.use('/admin/statistics/ticket', ticket_stats);
app.use('/admin/email', email);
app.post("/uploader", uploader);



/* GET home page. */
app.get('/', function(req, res) {
	req.session.user 	 	= null;
	req.session.lang 	 	= null;
	req.session.password 	= null;
	req.session.email 	 	= null;
	req.session.dependents 	= null;
	req.session.dni_letter	= null;
	req.session.name		= null;
	req.session.surname		= null;
	res.render('index');
});
app.get('/:lang', function(req, res) 
{
	req.session.lang = req.params.lang;
	//req.i18n.setLng(req.session.lang);
	res.redirect('users/user');
	//res.send(req.params.lang);
});


/// catch 404 and forward to error handler
app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
});

/// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
        res.status(err.status || 500);
        res.render('error', {
            message: err.message,
            error: err
        });
    });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
        message: err.message,
        error: {}
    });
});

module.exports = app;

```

I´d want to repeat that it is working fine on Windows, and the node_modules is not copied from the Windows folder.

Where is the problem??
Thanks!!

**Comment by jamuhl** [comment]
your code is written for i18next v1 not used in package.json v2.0.0

v2 uses https://github.com/i18next/i18next-express-middleware to integrate i18next to express.

a) migrate to v2
b) use old v1.10.6 (https://github.com/i18next/i18next-node)

**Comment by eloyucu** [comment]
OK!! I suppose that, one month ago, when I installed this module on my laptop (Windows) I downloaded an old version, but now the version changed.
Thank you.

**Comment by jamuhl** [comment]
sorry for that...
