### ISSUE TITLE
2.3.1 breaks: TypeError: i18n.use is not a function

### ISSUE THREAD

**Issue by arve0** [i18next/i18next#599]
An update to i18n seems to break builds.
- Here is a build from yesterday, [version 2.2.0](https://travis-ci.org/kodeklubben/oppgaver/builds/114628821#L704), works fine.
- A build right now, version [2.3.1](https://travis-ci.org/kodeklubben/oppgaver/builds/114897190#L702), [breaks on `.use`](https://travis-ci.org/kodeklubben/oppgaver/builds/114897190#L1226).

Full trace:
```
TypeError: i18n.use is not a function
    at Object.<anonymous> (i18n.js:7:4)
    at Module._compile (module.js:413:34)
    at loader (/home/travis/build/kodeklubben/oppgaver/codeclub_lesson_builder/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/kodeklubben/oppgaver/codeclub_lesson_builder/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (build.js:16:17)
    at Module._compile (module.js:413:34)
    at loader (/home/travis/build/kodeklubben/oppgaver/codeclub_lesson_builder/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/kodeklubben/oppgaver/codeclub_lesson_builder/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

**Comment by jamuhl** [comment]
how do you require i18next?

**Comment by arve0** [comment]
```
var i18n = require('i18next')
var backend = require('i18next-sync-fs-backend')
var config = require('./config.js')
var join = require('path').join

i18n
  .use(backend)
  .init({
    debug: false,
    lng: config.locales[0],
    whitelist: config.locales,
    fallbackLng: [],
    load: 'currentOnly',
    backend: {
      loadPath: join(config.i18nRoot, '{{lng}}/{{ns}}.json5')
    }
  }, function (err) {
    if (err) {
      console.log(err)
      throw new Error('i18next failed to initialize')
    }
  })

/**
 * Export the translate function.
 *
 * Usage:
 *    var translate = require('./i18n.js')
 *    translate('key')
 */
module.exports = i18n.getFixedT(config.locales[0])
```

**Comment by arve0** [comment]
Seems to be something in your build process:

![i18next](https://cloud.githubusercontent.com/assets/4810521/13651482/d4e3a442-e647-11e5-9961-19950f370e09.gif)

**Comment by jamuhl** [comment]
argh...can you try `var i18n = require('i18next').default`

babel 6 changed that....

**Comment by arve0** [comment]
Sure, as you can see in the gif, `i18n.default` would work. But this is a breaking change and should go as a major version bump.

**Comment by jamuhl** [comment]
honestly i did not expect this.

**Comment by jamuhl** [comment]
and as i no where use require anymore...i run into the trap :(

**Comment by arve0** [comment]
Would changing your `export default` to old `module.exports` work?

**Comment by arve0** [comment]
Since you only have the default export, the plugin mentioned in [so](http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default) might work.

**Comment by jamuhl** [comment]
can you try 2.3.3?

**Comment by jamuhl** [comment]
main is now index.js

`module.exports = require('./dist/commonjs/index.js').default;`

**Comment by arve0** [comment]
That works, thanks :+1:

**Comment by jamuhl** [comment]
great...
