### ISSUE TITLE
set fallbackLng on server side, returns TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by chinaq** [i18next/i18next#884]
I set fallbackLng by object as the document:

> 3.5.0
> - fallbackLng: { 'de-CH': ['fr', 'it', 'en'], 'de': ['fr', 'en'], 'zh-Hans': ['zh-Hant', 'en'], 'zh-Hant': ['zh-Hans', 'en'], 'default': ['en'] }

my package.json looks like this:
```
    "i18next": "^4.1.1",
    "i18next-browser-languagedetector": "^1.0.1",
    "i18next-express-middleware": "^1.0.2",
    "i18next-node-fs-backend": "^0.1.3",
    "i18next-xhr-backend": "^1.2.1",
```

This is my init:
```
i18n.use(i18nMiddleware.LanguageDetector).use(i18nFsBackend).init(
	whitelist: ['en', 'zh-CN', 'zh-Hans']
	fallbackLng: {'zh-Hans': ['zh-CN', 'en'], 'zh-CN': ['en'], 'default':['en']}
	backend:
		loadPath: path.resolve(__dirname, '../locales/{{lng}}/translation.json')
)

app.use i18nMiddleware.handle(i18n, {})
```

But I got the error:
```
E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\LanguageUtils.js:38
    if (code.indexOf('-') < 0) return null;
            ^

TypeError: Cannot read property 'indexOf' of undefined
    at LanguageUtil.getScriptPartFromCode (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\LanguageUtils.js:38:13)
    at LanguageUtil.getFallbackCodes (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\LanguageUtils.js:100:40)
    at LanguageUtil.toResolveHierarchy (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\LanguageUtils.js:110:30)
    at append (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\i18next.js:217:52)
    at E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\i18next.js:223:9
    at I18n.loadResources (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\i18next.js:234:8)
    at I18n.changeLanguage (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\i18next.js:301:10)
    at load [as _onTimeout] (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\i18next.js:186:14)
    at Timer.listOnTimeout (timers.js:92:15)
```

How can I solve it?

**Comment by jamuhl** [comment]
Hm...will add a fix there so if no lngCode we get no error.

Be aware to have the translations you will need to preload the locals you got:

```
i18n.use(i18nMiddleware.LanguageDetector).use(i18nFsBackend).init(
        preload: ['en', 'zh-CN', 'zh-Hans'],
	...
)
```

else they will be loaded on first request with that local -> but that first request will be translated to 'fallback'...

to workaround the current issue it should be enough to provide a `lng` on init:

```
i18n.use(i18nMiddleware.LanguageDetector).use(i18nFsBackend).init(
        lng: 'en',
        preload: ['en', 'zh-CN', 'zh-Hans'],
	...
)
```

**Comment by jamuhl** [comment]
a fix for this will be in next upcoming version https://github.com/i18next/i18next/commit/309c2953e9a67b01d586cc25e1e37a4fe963fce8 -> that will just not throw an error - you still will need to define some locals to preload.

**Comment by chinaq** [comment]
Thanks @jamuhl. It works on starting the server by adding lng, but it comes error on request:

```
TypeError: Cannot read property 'indexOf' of undefined
    at LanguageUtil.getScriptPartFromCode (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\LanguageUtils.js:38:13)
    at LanguageUtil.getFallbackCodes (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\LanguageUtils.js:100:40)
    at LanguageUtil.toResolveHierarchy (E:\Projects\Node\Coffee\Grasp\node_modules\i18next\dist\commonjs\LanguageUtils.js:110:30)
    at E:\Projects\Node\Coffee\Grasp\node_modules\i18next-express-middleware\lib\index.js:47:52
    at Layer.handle [as handle_request] (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:312:13)
    at E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:280:7
    at Function.process_params (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:330:12)
    at next (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:271:10)
    at expressInit (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:312:13)
    at E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:280:7
    at Function.process_params (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:330:12)
    at next (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:271:10)
    at query (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\middleware\query.js:49:5)
    at Layer.handle [as handle_request] (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:312:13)
    at E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:280:7
    at Function.process_params (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:330:12)
    at next (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:271:10)
    at Function.handle (E:\Projects\Node\Coffee\Grasp\node_modules\.4.13.4@express\lib\router\index.js:176:3)
```
How to fix this?

**Comment by jamuhl** [comment]
could you try with i18next@7.0.1 ?!?

**Comment by chinaq** [comment]
It works on 7.0.1. Great!
